# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
# turn off trigger

#trigger:
#- master
trigger: none

pool:
  vmImage: 'windows-latest'

variables:
  #solution: '**/FullFrameworkDemo/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetCommand@2
  displayName: 'Nuget Restore'
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'

- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    createLogFile: true
    configuration: 'debug'

- task: Bash@3
  displayName: 'Update WebApp Image Tag'
  inputs:
    targetType: 'inline'
    script: |
      bash -c "sed -i 's/BuildNumber/$(Build.BuildId)/g'  frontend-webapp.yaml"\

- task: Docker@2
  displayName: 'Build and Push WebApp'
  inputs:
    containerRegistry: 'contoso-acr'
    repository: 'webapp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)\FullFrameworkDemo'

- task: PublishBuildArtifacts@1
  displayName: 'Publish WebApp YAML file'
  inputs:
    PathtoPublish: 'frontend-webapp.yaml'
    ArtifactName: 'frontend-webapp'
    publishLocation: 'Container'

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Microsoft Azure Internal Consumption(18c9a476-0820-4be7-afc7-6d1fea9fd71e)'
    azureResourceGroup: 'rg-contoso-bikes'
    kubernetesCluster: 'contosobikes'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'frontend-webapp.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'Microsoft Azure Internal Consumption(18c9a476-0820-4be7-afc7-6d1fea9fd71e)'
    azureContainerRegistry: 'contosodemo.azurecr.io'
    secretName: 'acr'
