apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipewebapp
  labels:
    app: pipewebapp
spec:
  replicas: 1
  template:
    metadata:
      name: pipewebapp
      labels:
        app: pipewebapp
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows
      containers:
      - name: pipewebapp
        image: dockerdemoacr2.azurecr.io/pipelinebuiltwebapp:178
        resources:
          limits:
            cpu: 1
            memory: 800M
          requests:
            cpu: .1
            memory: 300M
        ports:
          - containerPort: 80
  selector:
    matchLabels:
      app: pipewebapp
---
apiVersion: v1
kind: Service
metadata:
  name: pipewebapp
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: pipewebapp